// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: liapoldus/peer/v1/peer.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallRequest opens a unary invocation. method is opaque and payload is an
// opaque application payload; neither side interprets either.
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CallResult carries a successful unary response payload.
type CallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResult) Reset() {
	*x = CallResult{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResult) ProtoMessage() {}

func (x *CallResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResult.ProtoReflect.Descriptor instead.
func (*CallResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *CallResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Status is the carrier-independent failure taxonomy. code is the numeric value
// of domain/peer.StatusCode. message must be a sanitized, non-sensitive summary:
// credentials, keys, tokens and configuration values never appear on this wire.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Failure terminates a call or a stream with a Status.
type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *Failure) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// OpenStream requests a bidirectional stream for an opaque method.
type OpenStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenStream) Reset() {
	*x = OpenStream{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenStream) ProtoMessage() {}

func (x *OpenStream) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenStream.ProtoReflect.Descriptor instead.
func (*OpenStream) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *OpenStream) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// StreamAccepted acknowledges OpenStream. The stream is established only once
// the requesting peer receives this, so a rejected method is reported by the
// request rather than by the first message.
type StreamAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAccepted) Reset() {
	*x = StreamAccepted{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAccepted) ProtoMessage() {}

func (x *StreamAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAccepted.ProtoReflect.Descriptor instead.
func (*StreamAccepted) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{5}
}

// Data carries one stream message. The receiver enforces its own
// MaxMessageBytes, so an oversized message is rejected rather than buffered.
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Close signals that the sender will send no further Data on a stream. It is the
// peer's cue to deliver io.EOF and is independent of session teardown.
type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{7}
}

// Ping and Pong form the liveness probe pair used to detect a dead connection.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_peer_v1_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_liapoldus_peer_v1_peer_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_liapoldus_peer_v1_peer_proto protoreflect.FileDescriptor

const file_liapoldus_peer_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x1cliapoldus/peer/v1/peer.proto\x12\x11liapoldus.peer.v1\"?\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"&\n" +
	"\n" +
	"CallResult\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\aFailure\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.liapoldus.peer.v1.StatusR\x06status\"$\n" +
	"\n" +
	"OpenStream\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\"\x10\n" +
	"\x0eStreamAccepted\" \n" +
	"\x04Data\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\a\n" +
	"\x05Close\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonceBFZDgithub.com/Liapoldus/pluginprotocol/v2/infrastructure/peer/wire;wireb\x06proto3"

var (
	file_liapoldus_peer_v1_peer_proto_rawDescOnce sync.Once
	file_liapoldus_peer_v1_peer_proto_rawDescData []byte
)

func file_liapoldus_peer_v1_peer_proto_rawDescGZIP() []byte {
	file_liapoldus_peer_v1_peer_proto_rawDescOnce.Do(func() {
		file_liapoldus_peer_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liapoldus_peer_v1_peer_proto_rawDesc), len(file_liapoldus_peer_v1_peer_proto_rawDesc)))
	})
	return file_liapoldus_peer_v1_peer_proto_rawDescData
}

var file_liapoldus_peer_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_liapoldus_peer_v1_peer_proto_goTypes = []any{
	(*CallRequest)(nil),    // 0: liapoldus.peer.v1.CallRequest
	(*CallResult)(nil),     // 1: liapoldus.peer.v1.CallResult
	(*Status)(nil),         // 2: liapoldus.peer.v1.Status
	(*Failure)(nil),        // 3: liapoldus.peer.v1.Failure
	(*OpenStream)(nil),     // 4: liapoldus.peer.v1.OpenStream
	(*StreamAccepted)(nil), // 5: liapoldus.peer.v1.StreamAccepted
	(*Data)(nil),           // 6: liapoldus.peer.v1.Data
	(*Close)(nil),          // 7: liapoldus.peer.v1.Close
	(*Ping)(nil),           // 8: liapoldus.peer.v1.Ping
	(*Pong)(nil),           // 9: liapoldus.peer.v1.Pong
}
var file_liapoldus_peer_v1_peer_proto_depIdxs = []int32{
	2, // 0: liapoldus.peer.v1.Failure.status:type_name -> liapoldus.peer.v1.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_liapoldus_peer_v1_peer_proto_init() }
func file_liapoldus_peer_v1_peer_proto_init() {
	if File_liapoldus_peer_v1_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liapoldus_peer_v1_peer_proto_rawDesc), len(file_liapoldus_peer_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_liapoldus_peer_v1_peer_proto_goTypes,
		DependencyIndexes: file_liapoldus_peer_v1_peer_proto_depIdxs,
		MessageInfos:      file_liapoldus_peer_v1_peer_proto_msgTypes,
	}.Build()
	File_liapoldus_peer_v1_peer_proto = out.File
	file_liapoldus_peer_v1_peer_proto_goTypes = nil
	file_liapoldus_peer_v1_peer_proto_depIdxs = nil
}
