import { readdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const root = fileURLToPath(new URL("../..", import.meta.url));
const layers = ["domain", "application", "infrastructure", "presentation"] as const;

async function packageSources(directory: string): Promise<string> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".go"))
      .map((entry) => readFile(`${directory}/${entry.name}`, "utf8")),
  );
  return files.join("\n");
}

describe("four-layer plugin protocol", () => {
  it("has exactly domain, application, infrastructure, and presentation roots", async () => {
    const entries = new Set(await readdir(root));
    for (const layer of layers) {
      expect(entries.has(layer), `${layer}/ must exist`).toBe(true);
    }
    // The single authoritative check that no retired surface came back: the compiler
    // would not object to an unreferenced legacy package, and no runtime scenario would
    // fail because of one.
    for (const stray of ["sdk", "transport", "pluginv1", "contracts", "compatibility", "grpc"]) {
      expect(entries.has(stray), `${stray}/ must not exist at the repository root`).toBe(false);
    }
  });

  it("keeps every layer focused on the generic peer package", async () => {
    for (const layer of layers) {
      expect((await readdir(`${root}/${layer}`)).sort(), `${layer}/ must only contain peer`).toEqual(["peer"]);
    }
  });

  it("keeps the public facade a presentation wrapper over application peer", async () => {
    const facade = await packageSources(`${root}/presentation/peer`);
    expect(facade).toMatch(/github\.com\/Liapoldus\/pluginprotocol\/v2\/application\/peer/);
    expect(facade).toMatch(/github\.com\/Liapoldus\/pluginprotocol\/v2\/domain\/peer/);
    // Choosing a carrier from a consumer's config is the facade's job, so it may reach
    // into infrastructure. What it may not do is re-export generated wire types, which
    // would put a generated contract into the public API surface; the assertion below
    // is on the selector, not on the path, so an aliased import cannot hide it.
    expect(facade).not.toMatch(/\bwire\.[A-Z]\w*/);
    expect(facade).not.toMatch(/grpc\./);
  });

  it("keeps generated wire types inside the infrastructure wire adapter", async () => {
    const wire = await readFile(`${root}/infrastructure/peer/wire/peer.pb.go`, "utf8");
    expect(wire).toContain("Code generated by protoc-gen-go");
    expect(wire).toContain("package wire");

    for (const layerPackage of ["domain/peer", "application/peer", "presentation/peer"]) {
      const source = await packageSources(`${root}/${layerPackage}`);
      expect(source, `${layerPackage} must not import generated wire types`).not.toContain("infrastructure/peer/wire");
      expect(source, `${layerPackage} must not import generated wire types`).not.toMatch(/\bwire\.[A-Z]\w*/);
    }
  });
});
