// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: liapoldus/plugin/v1/control.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{0}
}

type Manifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{2}
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultJson   string                 `protobuf:"bytes,4,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetDefaultJson() string {
	if x != nil {
		return x.DefaultJson
	}
	return ""
}

func (x *ConfigField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConfigApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplyRequest) Reset() {
	*x = ConfigApplyRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyRequest) ProtoMessage() {}

func (x *ConfigApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyRequest.ProtoReflect.Descriptor instead.
func (*ConfigApplyRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigApplyRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplyResult) Reset() {
	*x = ConfigApplyResult{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyResult) ProtoMessage() {}

func (x *ConfigApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyResult.ProtoReflect.Descriptor instead.
func (*ConfigApplyResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigApplyResult) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{7}
}

type ShutdownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResult) Reset() {
	*x = ShutdownResult{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResult) ProtoMessage() {}

func (x *ShutdownResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResult.ProtoReflect.Descriptor instead.
func (*ShutdownResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownResult) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

var File_liapoldus_plugin_v1_control_proto protoreflect.FileDescriptor

const file_liapoldus_plugin_v1_control_proto_rawDesc = "" +
	"\n" +
	"!liapoldus/plugin/v1/control.proto\x12\x13liapoldus.plugin.v1\"\x11\n" +
	"\x0fManifestRequest\"m\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\"\x15\n" +
	"\x13ConfigSchemaRequest\"\xb0\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12!\n" +
	"\fdefault_json\x18\x04 \x01(\tR\vdefaultJson\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"H\n" +
	"\fConfigSchema\x128\n" +
	"\x06fields\x18\x01 \x03(\v2 .liapoldus.plugin.v1.ConfigFieldR\x06fields\",\n" +
	"\x12ConfigApplyRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"-\n" +
	"\x11ConfigApplyResult\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\"\x11\n" +
	"\x0fShutdownRequest\"(\n" +
	"\x0eShutdownResult\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closedB7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_liapoldus_plugin_v1_control_proto_rawDescOnce sync.Once
	file_liapoldus_plugin_v1_control_proto_rawDescData []byte
)

func file_liapoldus_plugin_v1_control_proto_rawDescGZIP() []byte {
	file_liapoldus_plugin_v1_control_proto_rawDescOnce.Do(func() {
		file_liapoldus_plugin_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_control_proto_rawDesc), len(file_liapoldus_plugin_v1_control_proto_rawDesc)))
	})
	return file_liapoldus_plugin_v1_control_proto_rawDescData
}

var file_liapoldus_plugin_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_liapoldus_plugin_v1_control_proto_goTypes = []any{
	(*ManifestRequest)(nil),     // 0: liapoldus.plugin.v1.ManifestRequest
	(*Manifest)(nil),            // 1: liapoldus.plugin.v1.Manifest
	(*ConfigSchemaRequest)(nil), // 2: liapoldus.plugin.v1.ConfigSchemaRequest
	(*ConfigField)(nil),         // 3: liapoldus.plugin.v1.ConfigField
	(*ConfigSchema)(nil),        // 4: liapoldus.plugin.v1.ConfigSchema
	(*ConfigApplyRequest)(nil),  // 5: liapoldus.plugin.v1.ConfigApplyRequest
	(*ConfigApplyResult)(nil),   // 6: liapoldus.plugin.v1.ConfigApplyResult
	(*ShutdownRequest)(nil),     // 7: liapoldus.plugin.v1.ShutdownRequest
	(*ShutdownResult)(nil),      // 8: liapoldus.plugin.v1.ShutdownResult
}
var file_liapoldus_plugin_v1_control_proto_depIdxs = []int32{
	3, // 0: liapoldus.plugin.v1.ConfigSchema.fields:type_name -> liapoldus.plugin.v1.ConfigField
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_liapoldus_plugin_v1_control_proto_init() }
func file_liapoldus_plugin_v1_control_proto_init() {
	if File_liapoldus_plugin_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_control_proto_rawDesc), len(file_liapoldus_plugin_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_liapoldus_plugin_v1_control_proto_goTypes,
		DependencyIndexes: file_liapoldus_plugin_v1_control_proto_depIdxs,
		MessageInfos:      file_liapoldus_plugin_v1_control_proto_msgTypes,
	}.Build()
	File_liapoldus_plugin_v1_control_proto = out.File
	file_liapoldus_plugin_v1_control_proto_goTypes = nil
	file_liapoldus_plugin_v1_control_proto_depIdxs = nil
}
