// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: liapoldus/plugin/v1/control.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvocationMode int32

const (
	InvocationMode_INVOCATION_MODE_UNSPECIFIED InvocationMode = 0
	InvocationMode_INVOCATION_MODE_CALL        InvocationMode = 1
	InvocationMode_INVOCATION_MODE_HTTP_STREAM InvocationMode = 2
	InvocationMode_INVOCATION_MODE_WEBSOCKET   InvocationMode = 3
	InvocationMode_INVOCATION_MODE_SSE         InvocationMode = 4
	InvocationMode_INVOCATION_MODE_TCP         InvocationMode = 5
	InvocationMode_INVOCATION_MODE_UDP         InvocationMode = 6
)

// Enum value maps for InvocationMode.
var (
	InvocationMode_name = map[int32]string{
		0: "INVOCATION_MODE_UNSPECIFIED",
		1: "INVOCATION_MODE_CALL",
		2: "INVOCATION_MODE_HTTP_STREAM",
		3: "INVOCATION_MODE_WEBSOCKET",
		4: "INVOCATION_MODE_SSE",
		5: "INVOCATION_MODE_TCP",
		6: "INVOCATION_MODE_UDP",
	}
	InvocationMode_value = map[string]int32{
		"INVOCATION_MODE_UNSPECIFIED": 0,
		"INVOCATION_MODE_CALL":        1,
		"INVOCATION_MODE_HTTP_STREAM": 2,
		"INVOCATION_MODE_WEBSOCKET":   3,
		"INVOCATION_MODE_SSE":         4,
		"INVOCATION_MODE_TCP":         5,
		"INVOCATION_MODE_UDP":         6,
	}
)

func (x InvocationMode) Enum() *InvocationMode {
	p := new(InvocationMode)
	*p = x
	return p
}

func (x InvocationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvocationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_liapoldus_plugin_v1_control_proto_enumTypes[0].Descriptor()
}

func (InvocationMode) Type() protoreflect.EnumType {
	return &file_liapoldus_plugin_v1_control_proto_enumTypes[0]
}

func (x InvocationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvocationMode.Descriptor instead.
func (InvocationMode) EnumDescriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{0}
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{0}
}

// Bootstrap carries only operational connection information supplied by the
// Gateway. It must never contain plugin settings or secret material.
type BootstrapRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InstanceId          string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	GrantBrokerEndpoint string                 `protobuf:"bytes,2,opt,name=grant_broker_endpoint,json=grantBrokerEndpoint,proto3" json:"grant_broker_endpoint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *BootstrapRequest) GetGrantBrokerEndpoint() string {
	if x != nil {
		return x.GrantBrokerEndpoint
	}
	return ""
}

type BootstrapResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResult) Reset() {
	*x = BootstrapResult{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResult) ProtoMessage() {}

func (x *BootstrapResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResult.ProtoReflect.Descriptor instead.
func (*BootstrapResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type Manifest struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	Name                  string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities          []string                `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion       string                  `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	CapabilityDescriptors []*CapabilityDescriptor `protobuf:"bytes,4,rep,name=capability_descriptors,json=capabilityDescriptors,proto3" json:"capability_descriptors,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Manifest) GetCapabilityDescriptors() []*CapabilityDescriptor {
	if x != nil {
		return x.CapabilityDescriptors
	}
	return nil
}

type CapabilityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Modes         []InvocationMode       `protobuf:"varint,2,rep,packed,name=modes,proto3,enum=liapoldus.plugin.v1.InvocationMode" json:"modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityDescriptor) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityDescriptor) GetModes() []InvocationMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

// DispatchApply replaces the complete active data-plane authorization scope
// for one logical plugin instance on the connected replica. Applying a
// request is atomic: on failure, the previous generation remains active.
// Generations start at 1 and increase monotonically per replica. An identical
// request repeated at the current generation is idempotent; a stale generation
// or a different request at the current generation is rejected.
type DispatchApplyRequest struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Generation     uint64                     `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	InstanceId     string                     `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SettingsDigest string                     `protobuf:"bytes,3,opt,name=settings_digest,json=settingsDigest,proto3" json:"settings_digest,omitempty"`
	ReleaseDigest  string                     `protobuf:"bytes,4,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	Capabilities   []*CapabilityDispatchScope `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchApplyRequest) Reset() {
	*x = DispatchApplyRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchApplyRequest) ProtoMessage() {}

func (x *DispatchApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchApplyRequest.ProtoReflect.Descriptor instead.
func (*DispatchApplyRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *DispatchApplyRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DispatchApplyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DispatchApplyRequest) GetSettingsDigest() string {
	if x != nil {
		return x.SettingsDigest
	}
	return ""
}

func (x *DispatchApplyRequest) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

func (x *DispatchApplyRequest) GetCapabilities() []*CapabilityDispatchScope {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Each capability is unique in one request and has one or more unique,
// non-unspecified modes declared by the replica's Manifest. An empty
// capabilities list installs deny-all for this generation.
type CapabilityDispatchScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Modes         []InvocationMode       `protobuf:"varint,2,rep,packed,name=modes,proto3,enum=liapoldus.plugin.v1.InvocationMode" json:"modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDispatchScope) Reset() {
	*x = CapabilityDispatchScope{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDispatchScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDispatchScope) ProtoMessage() {}

func (x *CapabilityDispatchScope) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDispatchScope.ProtoReflect.Descriptor instead.
func (*CapabilityDispatchScope) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityDispatchScope) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityDispatchScope) GetModes() []InvocationMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

// A successful response is emitted only after this replica has installed the
// requested generation. replica_identity_uri identifies the connected remote
// replica and must match its URI SAN as verified by the Gateway TLS peer.
// Settings and release digests acknowledge the replica-local active values.
// dispatch_digest is a non-empty opaque identifier for the installed complete
// capability-to-mode scope; v1 does not standardize its encoding.
type DispatchApplyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Generation         uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	ReplicaIdentityUri string                 `protobuf:"bytes,2,opt,name=replica_identity_uri,json=replicaIdentityUri,proto3" json:"replica_identity_uri,omitempty"`
	ManifestDigest     string                 `protobuf:"bytes,3,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	SettingsDigest     string                 `protobuf:"bytes,4,opt,name=settings_digest,json=settingsDigest,proto3" json:"settings_digest,omitempty"`
	ReleaseDigest      string                 `protobuf:"bytes,5,opt,name=release_digest,json=releaseDigest,proto3" json:"release_digest,omitempty"`
	DispatchDigest     string                 `protobuf:"bytes,6,opt,name=dispatch_digest,json=dispatchDigest,proto3" json:"dispatch_digest,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DispatchApplyResponse) Reset() {
	*x = DispatchApplyResponse{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchApplyResponse) ProtoMessage() {}

func (x *DispatchApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchApplyResponse.ProtoReflect.Descriptor instead.
func (*DispatchApplyResponse) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchApplyResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DispatchApplyResponse) GetReplicaIdentityUri() string {
	if x != nil {
		return x.ReplicaIdentityUri
	}
	return ""
}

func (x *DispatchApplyResponse) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *DispatchApplyResponse) GetSettingsDigest() string {
	if x != nil {
		return x.SettingsDigest
	}
	return ""
}

func (x *DispatchApplyResponse) GetReleaseDigest() string {
	if x != nil {
		return x.ReleaseDigest
	}
	return ""
}

func (x *DispatchApplyResponse) GetDispatchDigest() string {
	if x != nil {
		return x.DispatchDigest
	}
	return ""
}

type ConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaRequest) Reset() {
	*x = ConfigSchemaRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaRequest) ProtoMessage() {}

func (x *ConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*ConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{8}
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultJson   string                 `protobuf:"bytes,4,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetDefaultJson() string {
	if x != nil {
		return x.DefaultJson
	}
	return ""
}

func (x *ConfigField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ConfigApply is a Gateway-pushed, atomic settings revision. config is the
// versioned JSON document with opaque references only; grants contain no
// secret bytes and are valid only for this instance/revision/reference.
type ConfigApplyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	SettingsRevision string                 `protobuf:"bytes,2,opt,name=settings_revision,json=settingsRevision,proto3" json:"settings_revision,omitempty"`
	Grants           []*ActiveGrant         `protobuf:"bytes,3,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigApplyRequest) Reset() {
	*x = ConfigApplyRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyRequest) ProtoMessage() {}

func (x *ConfigApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyRequest.ProtoReflect.Descriptor instead.
func (*ConfigApplyRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigApplyRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigApplyRequest) GetSettingsRevision() string {
	if x != nil {
		return x.SettingsRevision
	}
	return ""
}

func (x *ConfigApplyRequest) GetGrants() []*ActiveGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

// A plugin acknowledges the exact revision only after applying settings and
// resolving any required config-scoped grants in memory.
type ConfigApplyResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Applied          bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	SettingsRevision string                 `protobuf:"bytes,2,opt,name=settings_revision,json=settingsRevision,proto3" json:"settings_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigApplyResult) Reset() {
	*x = ConfigApplyResult{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyResult) ProtoMessage() {}

func (x *ConfigApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyResult.ProtoReflect.Descriptor instead.
func (*ConfigApplyResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigApplyResult) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ConfigApplyResult) GetSettingsRevision() string {
	if x != nil {
		return x.SettingsRevision
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{13}
}

type ShutdownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResult) Reset() {
	*x = ShutdownResult{}
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResult) ProtoMessage() {}

func (x *ShutdownResult) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResult.ProtoReflect.Descriptor instead.
func (*ShutdownResult) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *ShutdownResult) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

var File_liapoldus_plugin_v1_control_proto protoreflect.FileDescriptor

const file_liapoldus_plugin_v1_control_proto_rawDesc = "" +
	"\n" +
	"!liapoldus/plugin/v1/control.proto\x12\x13liapoldus.plugin.v1\x1a\x1fliapoldus/plugin/v1/grant.proto\"\x11\n" +
	"\x0fManifestRequest\"g\n" +
	"\x10BootstrapRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x122\n" +
	"\x15grant_broker_endpoint\x18\x02 \x01(\tR\x13grantBrokerEndpoint\"-\n" +
	"\x0fBootstrapResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xcf\x01\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12`\n" +
	"\x16capability_descriptors\x18\x04 \x03(\v2).liapoldus.plugin.v1.CapabilityDescriptorR\x15capabilityDescriptors\"q\n" +
	"\x14CapabilityDescriptor\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x129\n" +
	"\x05modes\x18\x02 \x03(\x0e2#.liapoldus.plugin.v1.InvocationModeR\x05modes\"\xf9\x01\n" +
	"\x14DispatchApplyRequest\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0fsettings_digest\x18\x03 \x01(\tR\x0esettingsDigest\x12%\n" +
	"\x0erelease_digest\x18\x04 \x01(\tR\rreleaseDigest\x12P\n" +
	"\fcapabilities\x18\x05 \x03(\v2,.liapoldus.plugin.v1.CapabilityDispatchScopeR\fcapabilities\"t\n" +
	"\x17CapabilityDispatchScope\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x129\n" +
	"\x05modes\x18\x02 \x03(\x0e2#.liapoldus.plugin.v1.InvocationModeR\x05modes\"\x8b\x02\n" +
	"\x15DispatchApplyResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x120\n" +
	"\x14replica_identity_uri\x18\x02 \x01(\tR\x12replicaIdentityUri\x12'\n" +
	"\x0fmanifest_digest\x18\x03 \x01(\tR\x0emanifestDigest\x12'\n" +
	"\x0fsettings_digest\x18\x04 \x01(\tR\x0esettingsDigest\x12%\n" +
	"\x0erelease_digest\x18\x05 \x01(\tR\rreleaseDigest\x12'\n" +
	"\x0fdispatch_digest\x18\x06 \x01(\tR\x0edispatchDigest\"\x15\n" +
	"\x13ConfigSchemaRequest\"\xb0\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12!\n" +
	"\fdefault_json\x18\x04 \x01(\tR\vdefaultJson\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"H\n" +
	"\fConfigSchema\x128\n" +
	"\x06fields\x18\x01 \x03(\v2 .liapoldus.plugin.v1.ConfigFieldR\x06fields\"\x93\x01\n" +
	"\x12ConfigApplyRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12+\n" +
	"\x11settings_revision\x18\x02 \x01(\tR\x10settingsRevision\x128\n" +
	"\x06grants\x18\x03 \x03(\v2 .liapoldus.plugin.v1.ActiveGrantR\x06grants\"Z\n" +
	"\x11ConfigApplyResult\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12+\n" +
	"\x11settings_revision\x18\x02 \x01(\tR\x10settingsRevision\"\x11\n" +
	"\x0fShutdownRequest\"(\n" +
	"\x0eShutdownResult\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed*\xd6\x01\n" +
	"\x0eInvocationMode\x12\x1f\n" +
	"\x1bINVOCATION_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INVOCATION_MODE_CALL\x10\x01\x12\x1f\n" +
	"\x1bINVOCATION_MODE_HTTP_STREAM\x10\x02\x12\x1d\n" +
	"\x19INVOCATION_MODE_WEBSOCKET\x10\x03\x12\x17\n" +
	"\x13INVOCATION_MODE_SSE\x10\x04\x12\x17\n" +
	"\x13INVOCATION_MODE_TCP\x10\x05\x12\x17\n" +
	"\x13INVOCATION_MODE_UDP\x10\x06B7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_liapoldus_plugin_v1_control_proto_rawDescOnce sync.Once
	file_liapoldus_plugin_v1_control_proto_rawDescData []byte
)

func file_liapoldus_plugin_v1_control_proto_rawDescGZIP() []byte {
	file_liapoldus_plugin_v1_control_proto_rawDescOnce.Do(func() {
		file_liapoldus_plugin_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_control_proto_rawDesc), len(file_liapoldus_plugin_v1_control_proto_rawDesc)))
	})
	return file_liapoldus_plugin_v1_control_proto_rawDescData
}

var file_liapoldus_plugin_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_liapoldus_plugin_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_liapoldus_plugin_v1_control_proto_goTypes = []any{
	(InvocationMode)(0),             // 0: liapoldus.plugin.v1.InvocationMode
	(*ManifestRequest)(nil),         // 1: liapoldus.plugin.v1.ManifestRequest
	(*BootstrapRequest)(nil),        // 2: liapoldus.plugin.v1.BootstrapRequest
	(*BootstrapResult)(nil),         // 3: liapoldus.plugin.v1.BootstrapResult
	(*Manifest)(nil),                // 4: liapoldus.plugin.v1.Manifest
	(*CapabilityDescriptor)(nil),    // 5: liapoldus.plugin.v1.CapabilityDescriptor
	(*DispatchApplyRequest)(nil),    // 6: liapoldus.plugin.v1.DispatchApplyRequest
	(*CapabilityDispatchScope)(nil), // 7: liapoldus.plugin.v1.CapabilityDispatchScope
	(*DispatchApplyResponse)(nil),   // 8: liapoldus.plugin.v1.DispatchApplyResponse
	(*ConfigSchemaRequest)(nil),     // 9: liapoldus.plugin.v1.ConfigSchemaRequest
	(*ConfigField)(nil),             // 10: liapoldus.plugin.v1.ConfigField
	(*ConfigSchema)(nil),            // 11: liapoldus.plugin.v1.ConfigSchema
	(*ConfigApplyRequest)(nil),      // 12: liapoldus.plugin.v1.ConfigApplyRequest
	(*ConfigApplyResult)(nil),       // 13: liapoldus.plugin.v1.ConfigApplyResult
	(*ShutdownRequest)(nil),         // 14: liapoldus.plugin.v1.ShutdownRequest
	(*ShutdownResult)(nil),          // 15: liapoldus.plugin.v1.ShutdownResult
	(*ActiveGrant)(nil),             // 16: liapoldus.plugin.v1.ActiveGrant
}
var file_liapoldus_plugin_v1_control_proto_depIdxs = []int32{
	5,  // 0: liapoldus.plugin.v1.Manifest.capability_descriptors:type_name -> liapoldus.plugin.v1.CapabilityDescriptor
	0,  // 1: liapoldus.plugin.v1.CapabilityDescriptor.modes:type_name -> liapoldus.plugin.v1.InvocationMode
	7,  // 2: liapoldus.plugin.v1.DispatchApplyRequest.capabilities:type_name -> liapoldus.plugin.v1.CapabilityDispatchScope
	0,  // 3: liapoldus.plugin.v1.CapabilityDispatchScope.modes:type_name -> liapoldus.plugin.v1.InvocationMode
	10, // 4: liapoldus.plugin.v1.ConfigSchema.fields:type_name -> liapoldus.plugin.v1.ConfigField
	16, // 5: liapoldus.plugin.v1.ConfigApplyRequest.grants:type_name -> liapoldus.plugin.v1.ActiveGrant
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_liapoldus_plugin_v1_control_proto_init() }
func file_liapoldus_plugin_v1_control_proto_init() {
	if File_liapoldus_plugin_v1_control_proto != nil {
		return
	}
	file_liapoldus_plugin_v1_grant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_control_proto_rawDesc), len(file_liapoldus_plugin_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_liapoldus_plugin_v1_control_proto_goTypes,
		DependencyIndexes: file_liapoldus_plugin_v1_control_proto_depIdxs,
		EnumInfos:         file_liapoldus_plugin_v1_control_proto_enumTypes,
		MessageInfos:      file_liapoldus_plugin_v1_control_proto_msgTypes,
	}.Build()
	File_liapoldus_plugin_v1_control_proto = out.File
	file_liapoldus_plugin_v1_control_proto_goTypes = nil
	file_liapoldus_plugin_v1_control_proto_depIdxs = nil
}
