// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/liapoldus/plugin/v1/envelope.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Envelope) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *Envelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_proto_liapoldus_plugin_v1_envelope_proto protoreflect.FileDescriptor

const file_proto_liapoldus_plugin_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"(proto/liapoldus/plugin/v1/envelope.proto\x12\x13liapoldus.plugin.v1\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x94\x02\n" +
	"\bEnvelope\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.liapoldus.plugin.v1.Envelope.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.liapoldus.plugin.v1.ErrorR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x06fields\x18\x03 \x03(\v2&.liapoldus.plugin.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_proto_liapoldus_plugin_v1_envelope_proto_rawDescOnce sync.Once
	file_proto_liapoldus_plugin_v1_envelope_proto_rawDescData []byte
)

func file_proto_liapoldus_plugin_v1_envelope_proto_rawDescGZIP() []byte {
	file_proto_liapoldus_plugin_v1_envelope_proto_rawDescOnce.Do(func() {
		file_proto_liapoldus_plugin_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_envelope_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_envelope_proto_rawDesc)))
	})
	return file_proto_liapoldus_plugin_v1_envelope_proto_rawDescData
}

var file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_liapoldus_plugin_v1_envelope_proto_goTypes = []any{
	(*Error)(nil),    // 0: liapoldus.plugin.v1.Error
	(*Envelope)(nil), // 1: liapoldus.plugin.v1.Envelope
	(*Event)(nil),    // 2: liapoldus.plugin.v1.Event
	nil,              // 3: liapoldus.plugin.v1.Envelope.MetadataEntry
	nil,              // 4: liapoldus.plugin.v1.Event.FieldsEntry
}
var file_proto_liapoldus_plugin_v1_envelope_proto_depIdxs = []int32{
	3, // 0: liapoldus.plugin.v1.Envelope.metadata:type_name -> liapoldus.plugin.v1.Envelope.MetadataEntry
	0, // 1: liapoldus.plugin.v1.Envelope.error:type_name -> liapoldus.plugin.v1.Error
	4, // 2: liapoldus.plugin.v1.Event.fields:type_name -> liapoldus.plugin.v1.Event.FieldsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_liapoldus_plugin_v1_envelope_proto_init() }
func file_proto_liapoldus_plugin_v1_envelope_proto_init() {
	if File_proto_liapoldus_plugin_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_envelope_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_liapoldus_plugin_v1_envelope_proto_goTypes,
		DependencyIndexes: file_proto_liapoldus_plugin_v1_envelope_proto_depIdxs,
		MessageInfos:      file_proto_liapoldus_plugin_v1_envelope_proto_msgTypes,
	}.Build()
	File_proto_liapoldus_plugin_v1_envelope_proto = out.File
	file_proto_liapoldus_plugin_v1_envelope_proto_goTypes = nil
	file_proto_liapoldus_plugin_v1_envelope_proto_depIdxs = nil
}
