// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/liapoldus/plugin/v1/frame.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameKind int32

const (
	FrameKind_FRAME_KIND_UNSPECIFIED FrameKind = 0
	FrameKind_CALL                   FrameKind = 1
	FrameKind_CALL_RESULT            FrameKind = 2
	FrameKind_STREAM_OPEN            FrameKind = 3
	FrameKind_STREAM_DATA            FrameKind = 4
	FrameKind_STREAM_CLOSE           FrameKind = 5
	FrameKind_CANCEL                 FrameKind = 6
	FrameKind_EVENT                  FrameKind = 7
	FrameKind_ERROR                  FrameKind = 8
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0: "FRAME_KIND_UNSPECIFIED",
		1: "CALL",
		2: "CALL_RESULT",
		3: "STREAM_OPEN",
		4: "STREAM_DATA",
		5: "STREAM_CLOSE",
		6: "CANCEL",
		7: "EVENT",
		8: "ERROR",
	}
	FrameKind_value = map[string]int32{
		"FRAME_KIND_UNSPECIFIED": 0,
		"CALL":                   1,
		"CALL_RESULT":            2,
		"STREAM_OPEN":            3,
		"STREAM_DATA":            4,
		"STREAM_CLOSE":           5,
		"CANCEL":                 6,
		"EVENT":                  7,
		"ERROR":                  8,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_liapoldus_plugin_v1_frame_proto_enumTypes[0].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_proto_liapoldus_plugin_v1_frame_proto_enumTypes[0]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_frame_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          FrameKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=liapoldus.plugin.v1.FrameKind" json:"kind,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StreamId      uint64                 `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_liapoldus_plugin_v1_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_FRAME_KIND_UNSPECIFIED
}

func (x *Frame) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Frame) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_liapoldus_plugin_v1_frame_proto protoreflect.FileDescriptor

const file_proto_liapoldus_plugin_v1_frame_proto_rawDesc = "" +
	"\n" +
	"%proto/liapoldus/plugin/v1/frame.proto\x12\x13liapoldus.plugin.v1\"\x91\x01\n" +
	"\x05Frame\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.liapoldus.plugin.v1.FrameKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\x04R\bstreamId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload*\x98\x01\n" +
	"\tFrameKind\x12\x1a\n" +
	"\x16FRAME_KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04CALL\x10\x01\x12\x0f\n" +
	"\vCALL_RESULT\x10\x02\x12\x0f\n" +
	"\vSTREAM_OPEN\x10\x03\x12\x0f\n" +
	"\vSTREAM_DATA\x10\x04\x12\x10\n" +
	"\fSTREAM_CLOSE\x10\x05\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x06\x12\t\n" +
	"\x05EVENT\x10\a\x12\t\n" +
	"\x05ERROR\x10\bB7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_proto_liapoldus_plugin_v1_frame_proto_rawDescOnce sync.Once
	file_proto_liapoldus_plugin_v1_frame_proto_rawDescData []byte
)

func file_proto_liapoldus_plugin_v1_frame_proto_rawDescGZIP() []byte {
	file_proto_liapoldus_plugin_v1_frame_proto_rawDescOnce.Do(func() {
		file_proto_liapoldus_plugin_v1_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_frame_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_frame_proto_rawDesc)))
	})
	return file_proto_liapoldus_plugin_v1_frame_proto_rawDescData
}

var file_proto_liapoldus_plugin_v1_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_liapoldus_plugin_v1_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_liapoldus_plugin_v1_frame_proto_goTypes = []any{
	(FrameKind)(0), // 0: liapoldus.plugin.v1.FrameKind
	(*Frame)(nil),  // 1: liapoldus.plugin.v1.Frame
}
var file_proto_liapoldus_plugin_v1_frame_proto_depIdxs = []int32{
	0, // 0: liapoldus.plugin.v1.Frame.kind:type_name -> liapoldus.plugin.v1.FrameKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_liapoldus_plugin_v1_frame_proto_init() }
func file_proto_liapoldus_plugin_v1_frame_proto_init() {
	if File_proto_liapoldus_plugin_v1_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_frame_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_frame_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_liapoldus_plugin_v1_frame_proto_goTypes,
		DependencyIndexes: file_proto_liapoldus_plugin_v1_frame_proto_depIdxs,
		EnumInfos:         file_proto_liapoldus_plugin_v1_frame_proto_enumTypes,
		MessageInfos:      file_proto_liapoldus_plugin_v1_frame_proto_msgTypes,
	}.Build()
	File_proto_liapoldus_plugin_v1_frame_proto = out.File
	file_proto_liapoldus_plugin_v1_frame_proto_goTypes = nil
	file_proto_liapoldus_plugin_v1_frame_proto_depIdxs = nil
}
