// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: liapoldus/plugin/v1/grant.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrantBroker_RedeemGrant_FullMethodName = "/liapoldus.plugin.v1.GrantBroker/RedeemGrant"
)

// GrantBrokerClient is the client API for GrantBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrantBroker is hosted by Gateway on a private loopback endpoint. Plugins
// redeem opaque, per-call handles; secret material is never part of Call JSON.
type GrantBrokerClient interface {
	RedeemGrant(ctx context.Context, in *RedeemGrantRequest, opts ...grpc.CallOption) (*RedeemGrantResponse, error)
}

type grantBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrantBrokerClient(cc grpc.ClientConnInterface) GrantBrokerClient {
	return &grantBrokerClient{cc}
}

func (c *grantBrokerClient) RedeemGrant(ctx context.Context, in *RedeemGrantRequest, opts ...grpc.CallOption) (*RedeemGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemGrantResponse)
	err := c.cc.Invoke(ctx, GrantBroker_RedeemGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrantBrokerServer is the server API for GrantBroker service.
// All implementations must embed UnimplementedGrantBrokerServer
// for forward compatibility.
//
// GrantBroker is hosted by Gateway on a private loopback endpoint. Plugins
// redeem opaque, per-call handles; secret material is never part of Call JSON.
type GrantBrokerServer interface {
	RedeemGrant(context.Context, *RedeemGrantRequest) (*RedeemGrantResponse, error)
	mustEmbedUnimplementedGrantBrokerServer()
}

// UnimplementedGrantBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrantBrokerServer struct{}

func (UnimplementedGrantBrokerServer) RedeemGrant(context.Context, *RedeemGrantRequest) (*RedeemGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemGrant not implemented")
}
func (UnimplementedGrantBrokerServer) mustEmbedUnimplementedGrantBrokerServer() {}
func (UnimplementedGrantBrokerServer) testEmbeddedByValue()                     {}

// UnsafeGrantBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrantBrokerServer will
// result in compilation errors.
type UnsafeGrantBrokerServer interface {
	mustEmbedUnimplementedGrantBrokerServer()
}

func RegisterGrantBrokerServer(s grpc.ServiceRegistrar, srv GrantBrokerServer) {
	// If the following call panics, it indicates UnimplementedGrantBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrantBroker_ServiceDesc, srv)
}

func _GrantBroker_RedeemGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrantBrokerServer).RedeemGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrantBroker_RedeemGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrantBrokerServer).RedeemGrant(ctx, req.(*RedeemGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrantBroker_ServiceDesc is the grpc.ServiceDesc for GrantBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrantBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liapoldus.plugin.v1.GrantBroker",
	HandlerType: (*GrantBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedeemGrant",
			Handler:    _GrantBroker_RedeemGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "liapoldus/plugin/v1/grant.proto",
}
