// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: liapoldus/plugin/v1/grant.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActiveGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Domains       []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveGrant) Reset() {
	*x = ActiveGrant{}
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveGrant) ProtoMessage() {}

func (x *ActiveGrant) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveGrant.ProtoReflect.Descriptor instead.
func (*ActiveGrant) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_grant_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveGrant) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ActiveGrant) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ActiveGrant) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type RedeemGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemGrantRequest) Reset() {
	*x = RedeemGrantRequest{}
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemGrantRequest) ProtoMessage() {}

func (x *RedeemGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemGrantRequest.ProtoReflect.Descriptor instead.
func (*RedeemGrantRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_grant_proto_rawDescGZIP(), []int{1}
}

func (x *RedeemGrantRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *RedeemGrantRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *RedeemGrantRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type RedeemGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemGrantResponse) Reset() {
	*x = RedeemGrantResponse{}
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemGrantResponse) ProtoMessage() {}

func (x *RedeemGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemGrantResponse.ProtoReflect.Descriptor instead.
func (*RedeemGrantResponse) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_grant_proto_rawDescGZIP(), []int{2}
}

func (x *RedeemGrantResponse) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_liapoldus_plugin_v1_grant_proto protoreflect.FileDescriptor

const file_liapoldus_plugin_v1_grant_proto_rawDesc = "" +
	"\n" +
	"\x1fliapoldus/plugin/v1/grant.proto\x12\x13liapoldus.plugin.v1\"Y\n" +
	"\vActiveGrant\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\"^\n" +
	"\x12RedeemGrantRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"-\n" +
	"\x13RedeemGrantResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret2o\n" +
	"\vGrantBroker\x12`\n" +
	"\vRedeemGrant\x12'.liapoldus.plugin.v1.RedeemGrantRequest\x1a(.liapoldus.plugin.v1.RedeemGrantResponseB7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_liapoldus_plugin_v1_grant_proto_rawDescOnce sync.Once
	file_liapoldus_plugin_v1_grant_proto_rawDescData []byte
)

func file_liapoldus_plugin_v1_grant_proto_rawDescGZIP() []byte {
	file_liapoldus_plugin_v1_grant_proto_rawDescOnce.Do(func() {
		file_liapoldus_plugin_v1_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_grant_proto_rawDesc), len(file_liapoldus_plugin_v1_grant_proto_rawDesc)))
	})
	return file_liapoldus_plugin_v1_grant_proto_rawDescData
}

var file_liapoldus_plugin_v1_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_liapoldus_plugin_v1_grant_proto_goTypes = []any{
	(*ActiveGrant)(nil),         // 0: liapoldus.plugin.v1.ActiveGrant
	(*RedeemGrantRequest)(nil),  // 1: liapoldus.plugin.v1.RedeemGrantRequest
	(*RedeemGrantResponse)(nil), // 2: liapoldus.plugin.v1.RedeemGrantResponse
}
var file_liapoldus_plugin_v1_grant_proto_depIdxs = []int32{
	1, // 0: liapoldus.plugin.v1.GrantBroker.RedeemGrant:input_type -> liapoldus.plugin.v1.RedeemGrantRequest
	2, // 1: liapoldus.plugin.v1.GrantBroker.RedeemGrant:output_type -> liapoldus.plugin.v1.RedeemGrantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_liapoldus_plugin_v1_grant_proto_init() }
func file_liapoldus_plugin_v1_grant_proto_init() {
	if File_liapoldus_plugin_v1_grant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_grant_proto_rawDesc), len(file_liapoldus_plugin_v1_grant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liapoldus_plugin_v1_grant_proto_goTypes,
		DependencyIndexes: file_liapoldus_plugin_v1_grant_proto_depIdxs,
		MessageInfos:      file_liapoldus_plugin_v1_grant_proto_msgTypes,
	}.Build()
	File_liapoldus_plugin_v1_grant_proto = out.File
	file_liapoldus_plugin_v1_grant_proto_goTypes = nil
	file_liapoldus_plugin_v1_grant_proto_depIdxs = nil
}
