// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/liapoldus/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameKind int32

const (
	FrameKind_FRAME_KIND_UNSPECIFIED FrameKind = 0
	FrameKind_CALL                   FrameKind = 1
	FrameKind_CALL_RESULT            FrameKind = 2
	FrameKind_STREAM_OPEN            FrameKind = 3
	FrameKind_STREAM_DATA            FrameKind = 4
	FrameKind_STREAM_CLOSE           FrameKind = 5
	FrameKind_CANCEL                 FrameKind = 6
	FrameKind_EVENT                  FrameKind = 7
	FrameKind_ERROR                  FrameKind = 8
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0: "FRAME_KIND_UNSPECIFIED",
		1: "CALL",
		2: "CALL_RESULT",
		3: "STREAM_OPEN",
		4: "STREAM_DATA",
		5: "STREAM_CLOSE",
		6: "CANCEL",
		7: "EVENT",
		8: "ERROR",
	}
	FrameKind_value = map[string]int32{
		"FRAME_KIND_UNSPECIFIED": 0,
		"CALL":                   1,
		"CALL_RESULT":            2,
		"STREAM_OPEN":            3,
		"STREAM_DATA":            4,
		"STREAM_CLOSE":           5,
		"CANCEL":                 6,
		"EVENT":                  7,
		"ERROR":                  8,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_liapoldus_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_proto_liapoldus_plugin_v1_plugin_proto_enumTypes[0]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          FrameKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=liapoldus.plugin.v1.FrameKind" json:"kind,omitempty"`
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StreamId      uint64                 `protobuf:"varint,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_FRAME_KIND_UNSPECIFIED
}

func (x *Frame) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Frame) GetStreamId() uint64 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Envelope) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *Envelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Manifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Manifest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Health) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultJson   string                 `protobuf:"bytes,4,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetDefaultJson() string {
	if x != nil {
		return x.DefaultJson
	}
	return ""
}

func (x *ConfigField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConfigApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplyResult) Reset() {
	*x = ConfigApplyResult{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplyResult) ProtoMessage() {}

func (x *ConfigApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplyResult.ProtoReflect.Descriptor instead.
func (*ConfigApplyResult) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigApplyResult) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type ShutdownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Closed        bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResult) Reset() {
	*x = ShutdownResult{}
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResult) ProtoMessage() {}

func (x *ShutdownResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResult.ProtoReflect.Descriptor instead.
func (*ShutdownResult) Descriptor() ([]byte, []int) {
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ShutdownResult) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

var File_proto_liapoldus_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_liapoldus_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"&proto/liapoldus/plugin/v1/plugin.proto\x12\x13liapoldus.plugin.v1\"\x91\x01\n" +
	"\x05Frame\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.liapoldus.plugin.v1.FrameKindR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\x04R\bstreamId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\x94\x02\n" +
	"\bEnvelope\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.liapoldus.plugin.v1.Envelope.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x120\n" +
	"\x05error\x18\x05 \x01(\v2\x1a.liapoldus.plugin.v1.ErrorR\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x06fields\x18\x03 \x03(\v2&.liapoldus.plugin.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\"\x1e\n" +
	"\x06Health\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xb0\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12!\n" +
	"\fdefault_json\x18\x04 \x01(\tR\vdefaultJson\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"H\n" +
	"\fConfigSchema\x128\n" +
	"\x06fields\x18\x01 \x03(\v2 .liapoldus.plugin.v1.ConfigFieldR\x06fields\"-\n" +
	"\x11ConfigApplyResult\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\"(\n" +
	"\x0eShutdownResult\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed*\x98\x01\n" +
	"\tFrameKind\x12\x1a\n" +
	"\x16FRAME_KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04CALL\x10\x01\x12\x0f\n" +
	"\vCALL_RESULT\x10\x02\x12\x0f\n" +
	"\vSTREAM_OPEN\x10\x03\x12\x0f\n" +
	"\vSTREAM_DATA\x10\x04\x12\x10\n" +
	"\fSTREAM_CLOSE\x10\x05\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x06\x12\t\n" +
	"\x05EVENT\x10\a\x12\t\n" +
	"\x05ERROR\x10\bB7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_proto_liapoldus_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_liapoldus_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_liapoldus_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_liapoldus_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_liapoldus_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_plugin_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_liapoldus_plugin_v1_plugin_proto_rawDescData
}

var file_proto_liapoldus_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_liapoldus_plugin_v1_plugin_proto_goTypes = []any{
	(FrameKind)(0),            // 0: liapoldus.plugin.v1.FrameKind
	(*Frame)(nil),             // 1: liapoldus.plugin.v1.Frame
	(*Error)(nil),             // 2: liapoldus.plugin.v1.Error
	(*Envelope)(nil),          // 3: liapoldus.plugin.v1.Envelope
	(*Event)(nil),             // 4: liapoldus.plugin.v1.Event
	(*Manifest)(nil),          // 5: liapoldus.plugin.v1.Manifest
	(*Health)(nil),            // 6: liapoldus.plugin.v1.Health
	(*ConfigField)(nil),       // 7: liapoldus.plugin.v1.ConfigField
	(*ConfigSchema)(nil),      // 8: liapoldus.plugin.v1.ConfigSchema
	(*ConfigApplyResult)(nil), // 9: liapoldus.plugin.v1.ConfigApplyResult
	(*ShutdownResult)(nil),    // 10: liapoldus.plugin.v1.ShutdownResult
	nil,                       // 11: liapoldus.plugin.v1.Envelope.MetadataEntry
	nil,                       // 12: liapoldus.plugin.v1.Event.FieldsEntry
}
var file_proto_liapoldus_plugin_v1_plugin_proto_depIdxs = []int32{
	0,  // 0: liapoldus.plugin.v1.Frame.kind:type_name -> liapoldus.plugin.v1.FrameKind
	11, // 1: liapoldus.plugin.v1.Envelope.metadata:type_name -> liapoldus.plugin.v1.Envelope.MetadataEntry
	2,  // 2: liapoldus.plugin.v1.Envelope.error:type_name -> liapoldus.plugin.v1.Error
	12, // 3: liapoldus.plugin.v1.Event.fields:type_name -> liapoldus.plugin.v1.Event.FieldsEntry
	7,  // 4: liapoldus.plugin.v1.ConfigSchema.fields:type_name -> liapoldus.plugin.v1.ConfigField
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_liapoldus_plugin_v1_plugin_proto_init() }
func file_proto_liapoldus_plugin_v1_plugin_proto_init() {
	if File_proto_liapoldus_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_liapoldus_plugin_v1_plugin_proto_rawDesc), len(file_proto_liapoldus_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_liapoldus_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_liapoldus_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_liapoldus_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_liapoldus_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_liapoldus_plugin_v1_plugin_proto = out.File
	file_proto_liapoldus_plugin_v1_plugin_proto_goTypes = nil
	file_proto_liapoldus_plugin_v1_plugin_proto_depIdxs = nil
}
