// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: liapoldus/plugin/v1/service.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CallRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Capability string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*StreamMessage_Payload
	//	*StreamMessage_Event
	Body          isStreamMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_liapoldus_plugin_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_liapoldus_plugin_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamMessage) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *StreamMessage) GetBody() isStreamMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamMessage) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *StreamMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*StreamMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isStreamMessage_Body interface {
	isStreamMessage_Body()
}

type StreamMessage_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

type StreamMessage_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*StreamMessage_Payload) isStreamMessage_Body() {}

func (*StreamMessage_Event) isStreamMessage_Body() {}

var File_liapoldus_plugin_v1_service_proto protoreflect.FileDescriptor

const file_liapoldus_plugin_v1_service_proto_rawDesc = "" +
	"\n" +
	"!liapoldus/plugin/v1/service.proto\x12\x13liapoldus.plugin.v1\x1a!liapoldus/plugin/v1/control.proto\x1a\"liapoldus/plugin/v1/envelope.proto\"G\n" +
	"\vCallRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"V\n" +
	"\fCallResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x87\x01\n" +
	"\rStreamMessage\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x122\n" +
	"\x05event\x18\x03 \x01(\v2\x1a.liapoldus.plugin.v1.EventH\x00R\x05eventB\x06\n" +
	"\x04body2\x97\x04\n" +
	"\rPluginService\x12O\n" +
	"\bManifest\x12$.liapoldus.plugin.v1.ManifestRequest\x1a\x1d.liapoldus.plugin.v1.Manifest\x12[\n" +
	"\fConfigSchema\x12(.liapoldus.plugin.v1.ConfigSchemaRequest\x1a!.liapoldus.plugin.v1.ConfigSchema\x12^\n" +
	"\vConfigApply\x12'.liapoldus.plugin.v1.ConfigApplyRequest\x1a&.liapoldus.plugin.v1.ConfigApplyResult\x12U\n" +
	"\bShutdown\x12$.liapoldus.plugin.v1.ShutdownRequest\x1a#.liapoldus.plugin.v1.ShutdownResult\x12K\n" +
	"\x04Call\x12 .liapoldus.plugin.v1.CallRequest\x1a!.liapoldus.plugin.v1.CallResponse\x12T\n" +
	"\x06Stream\x12\".liapoldus.plugin.v1.StreamMessage\x1a\".liapoldus.plugin.v1.StreamMessage(\x010\x01B7Z5github.com/Liapoldus/pluginprotocol/pluginv1;pluginv1b\x06proto3"

var (
	file_liapoldus_plugin_v1_service_proto_rawDescOnce sync.Once
	file_liapoldus_plugin_v1_service_proto_rawDescData []byte
)

func file_liapoldus_plugin_v1_service_proto_rawDescGZIP() []byte {
	file_liapoldus_plugin_v1_service_proto_rawDescOnce.Do(func() {
		file_liapoldus_plugin_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_service_proto_rawDesc), len(file_liapoldus_plugin_v1_service_proto_rawDesc)))
	})
	return file_liapoldus_plugin_v1_service_proto_rawDescData
}

var file_liapoldus_plugin_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_liapoldus_plugin_v1_service_proto_goTypes = []any{
	(*CallRequest)(nil),         // 0: liapoldus.plugin.v1.CallRequest
	(*CallResponse)(nil),        // 1: liapoldus.plugin.v1.CallResponse
	(*StreamMessage)(nil),       // 2: liapoldus.plugin.v1.StreamMessage
	(*Event)(nil),               // 3: liapoldus.plugin.v1.Event
	(*ManifestRequest)(nil),     // 4: liapoldus.plugin.v1.ManifestRequest
	(*ConfigSchemaRequest)(nil), // 5: liapoldus.plugin.v1.ConfigSchemaRequest
	(*ConfigApplyRequest)(nil),  // 6: liapoldus.plugin.v1.ConfigApplyRequest
	(*ShutdownRequest)(nil),     // 7: liapoldus.plugin.v1.ShutdownRequest
	(*Manifest)(nil),            // 8: liapoldus.plugin.v1.Manifest
	(*ConfigSchema)(nil),        // 9: liapoldus.plugin.v1.ConfigSchema
	(*ConfigApplyResult)(nil),   // 10: liapoldus.plugin.v1.ConfigApplyResult
	(*ShutdownResult)(nil),      // 11: liapoldus.plugin.v1.ShutdownResult
}
var file_liapoldus_plugin_v1_service_proto_depIdxs = []int32{
	3,  // 0: liapoldus.plugin.v1.StreamMessage.event:type_name -> liapoldus.plugin.v1.Event
	4,  // 1: liapoldus.plugin.v1.PluginService.Manifest:input_type -> liapoldus.plugin.v1.ManifestRequest
	5,  // 2: liapoldus.plugin.v1.PluginService.ConfigSchema:input_type -> liapoldus.plugin.v1.ConfigSchemaRequest
	6,  // 3: liapoldus.plugin.v1.PluginService.ConfigApply:input_type -> liapoldus.plugin.v1.ConfigApplyRequest
	7,  // 4: liapoldus.plugin.v1.PluginService.Shutdown:input_type -> liapoldus.plugin.v1.ShutdownRequest
	0,  // 5: liapoldus.plugin.v1.PluginService.Call:input_type -> liapoldus.plugin.v1.CallRequest
	2,  // 6: liapoldus.plugin.v1.PluginService.Stream:input_type -> liapoldus.plugin.v1.StreamMessage
	8,  // 7: liapoldus.plugin.v1.PluginService.Manifest:output_type -> liapoldus.plugin.v1.Manifest
	9,  // 8: liapoldus.plugin.v1.PluginService.ConfigSchema:output_type -> liapoldus.plugin.v1.ConfigSchema
	10, // 9: liapoldus.plugin.v1.PluginService.ConfigApply:output_type -> liapoldus.plugin.v1.ConfigApplyResult
	11, // 10: liapoldus.plugin.v1.PluginService.Shutdown:output_type -> liapoldus.plugin.v1.ShutdownResult
	1,  // 11: liapoldus.plugin.v1.PluginService.Call:output_type -> liapoldus.plugin.v1.CallResponse
	2,  // 12: liapoldus.plugin.v1.PluginService.Stream:output_type -> liapoldus.plugin.v1.StreamMessage
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_liapoldus_plugin_v1_service_proto_init() }
func file_liapoldus_plugin_v1_service_proto_init() {
	if File_liapoldus_plugin_v1_service_proto != nil {
		return
	}
	file_liapoldus_plugin_v1_control_proto_init()
	file_liapoldus_plugin_v1_envelope_proto_init()
	file_liapoldus_plugin_v1_service_proto_msgTypes[2].OneofWrappers = []any{
		(*StreamMessage_Payload)(nil),
		(*StreamMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liapoldus_plugin_v1_service_proto_rawDesc), len(file_liapoldus_plugin_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liapoldus_plugin_v1_service_proto_goTypes,
		DependencyIndexes: file_liapoldus_plugin_v1_service_proto_depIdxs,
		MessageInfos:      file_liapoldus_plugin_v1_service_proto_msgTypes,
	}.Build()
	File_liapoldus_plugin_v1_service_proto = out.File
	file_liapoldus_plugin_v1_service_proto_goTypes = nil
	file_liapoldus_plugin_v1_service_proto_depIdxs = nil
}
